### PR TITLE
Remove anonymous bind

### PR DESCRIPTION
**Pull request by rajnikantsh**
Remove anonymous bind

### CODE REVIEW

**Comment by yurem** [comment]
Is it for issue #539?

Why we remove this check box from facelet ox:ldapConfig? We reuses it in other places too. If we just not need to render it in Cache Refresh we can specify attribute useAnonymousBind="false". Also in this case we don't need to remove references to this box from code. I remember some time ago we got issue to add it from one customer

**Comment by nynymike** [comment]
I remember the customer who asked for it, but it wasn't working...

**Comment by yurem** [comment]
I'm ok to remove this box from CR form, but we need too keep it in customAuthenticationForm.xhtml

**Comment by rajnikantsh** [comment]
Now i have remove anonymous bind only from CR form. resolve #159

**Comment by yurem** [comment]
Why in this request you replaced ox:decorate with s:decorate? Also there is no definition of facelet variable `useAnonymousBind`

**Pull request closed without merging**
